/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestesRouteImport } from './routes/testes'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as OiRouteImport } from './routes/oi'
import { Route as ManuaisAvaliacaoRouteImport } from './routes/manuais-avaliacao'
import { Route as ManuaisRouteImport } from './routes/manuais'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EscalaRouteImport } from './routes/escala'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CronogramaRouteImport } from './routes/cronograma'
import { Route as BloqueadoRouteImport } from './routes/bloqueado'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEquipeOverrideRouteImport } from './routes/api/equipe-override'
import { Route as CronogramaPublicoTokenRouteImport } from './routes/cronograma/publico/$token'

const TestesRoute = TestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const OiRoute = OiRouteImport.update({
  id: '/oi',
  path: '/oi',
  getParentRoute: () => rootRouteImport,
} as any)
const ManuaisAvaliacaoRoute = ManuaisAvaliacaoRouteImport.update({
  id: '/manuais-avaliacao',
  path: '/manuais-avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ManuaisRoute = ManuaisRouteImport.update({
  id: '/manuais',
  path: '/manuais',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalaRoute = EscalaRouteImport.update({
  id: '/escala',
  path: '/escala',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaRoute = CronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => rootRouteImport,
} as any)
const BloqueadoRoute = BloqueadoRouteImport.update({
  id: '/bloqueado',
  path: '/bloqueado',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEquipeOverrideRoute = ApiEquipeOverrideRouteImport.update({
  id: '/api/equipe-override',
  path: '/api/equipe-override',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaPublicoTokenRoute = CronogramaPublicoTokenRouteImport.update({
  id: '/publico/$token',
  path: '/publico/$token',
  getParentRoute: () => CronogramaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/backlog': typeof BacklogRoute
  '/bloqueado': typeof BloqueadoRoute
  '/cronograma': typeof CronogramaRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/escala': typeof EscalaRoute
  '/estoque': typeof EstoqueRoute
  '/login': typeof LoginRoute
  '/manuais': typeof ManuaisRoute
  '/manuais-avaliacao': typeof ManuaisAvaliacaoRoute
  '/oi': typeof OiRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/relatorio': typeof RelatorioRoute
  '/testes': typeof TestesRoute
  '/api/equipe-override': typeof ApiEquipeOverrideRoute
  '/cronograma/publico/$token': typeof CronogramaPublicoTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/backlog': typeof BacklogRoute
  '/bloqueado': typeof BloqueadoRoute
  '/cronograma': typeof CronogramaRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/escala': typeof EscalaRoute
  '/estoque': typeof EstoqueRoute
  '/login': typeof LoginRoute
  '/manuais': typeof ManuaisRoute
  '/manuais-avaliacao': typeof ManuaisAvaliacaoRoute
  '/oi': typeof OiRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/relatorio': typeof RelatorioRoute
  '/testes': typeof TestesRoute
  '/api/equipe-override': typeof ApiEquipeOverrideRoute
  '/cronograma/publico/$token': typeof CronogramaPublicoTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/backlog': typeof BacklogRoute
  '/bloqueado': typeof BloqueadoRoute
  '/cronograma': typeof CronogramaRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/escala': typeof EscalaRoute
  '/estoque': typeof EstoqueRoute
  '/login': typeof LoginRoute
  '/manuais': typeof ManuaisRoute
  '/manuais-avaliacao': typeof ManuaisAvaliacaoRoute
  '/oi': typeof OiRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/relatorio': typeof RelatorioRoute
  '/testes': typeof TestesRoute
  '/api/equipe-override': typeof ApiEquipeOverrideRoute
  '/cronograma/publico/$token': typeof CronogramaPublicoTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/backlog'
    | '/bloqueado'
    | '/cronograma'
    | '/dashboard'
    | '/escala'
    | '/estoque'
    | '/login'
    | '/manuais'
    | '/manuais-avaliacao'
    | '/oi'
    | '/pending'
    | '/register'
    | '/relatorio'
    | '/testes'
    | '/api/equipe-override'
    | '/cronograma/publico/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/backlog'
    | '/bloqueado'
    | '/cronograma'
    | '/dashboard'
    | '/escala'
    | '/estoque'
    | '/login'
    | '/manuais'
    | '/manuais-avaliacao'
    | '/oi'
    | '/pending'
    | '/register'
    | '/relatorio'
    | '/testes'
    | '/api/equipe-override'
    | '/cronograma/publico/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/backlog'
    | '/bloqueado'
    | '/cronograma'
    | '/dashboard'
    | '/escala'
    | '/estoque'
    | '/login'
    | '/manuais'
    | '/manuais-avaliacao'
    | '/oi'
    | '/pending'
    | '/register'
    | '/relatorio'
    | '/testes'
    | '/api/equipe-override'
    | '/cronograma/publico/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BacklogRoute: typeof BacklogRoute
  BloqueadoRoute: typeof BloqueadoRoute
  CronogramaRoute: typeof CronogramaRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EscalaRoute: typeof EscalaRoute
  EstoqueRoute: typeof EstoqueRoute
  LoginRoute: typeof LoginRoute
  ManuaisRoute: typeof ManuaisRoute
  ManuaisAvaliacaoRoute: typeof ManuaisAvaliacaoRoute
  OiRoute: typeof OiRoute
  PendingRoute: typeof PendingRoute
  RegisterRoute: typeof RegisterRoute
  RelatorioRoute: typeof RelatorioRoute
  TestesRoute: typeof TestesRoute
  ApiEquipeOverrideRoute: typeof ApiEquipeOverrideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testes': {
      id: '/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof TestesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oi': {
      id: '/oi'
      path: '/oi'
      fullPath: '/oi'
      preLoaderRoute: typeof OiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuais-avaliacao': {
      id: '/manuais-avaliacao'
      path: '/manuais-avaliacao'
      fullPath: '/manuais-avaliacao'
      preLoaderRoute: typeof ManuaisAvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuais': {
      id: '/manuais'
      path: '/manuais'
      fullPath: '/manuais'
      preLoaderRoute: typeof ManuaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escala': {
      id: '/escala'
      path: '/escala'
      fullPath: '/escala'
      preLoaderRoute: typeof EscalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma': {
      id: '/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof CronogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloqueado': {
      id: '/bloqueado'
      path: '/bloqueado'
      fullPath: '/bloqueado'
      preLoaderRoute: typeof BloqueadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/equipe-override': {
      id: '/api/equipe-override'
      path: '/api/equipe-override'
      fullPath: '/api/equipe-override'
      preLoaderRoute: typeof ApiEquipeOverrideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma/publico/$token': {
      id: '/cronograma/publico/$token'
      path: '/publico/$token'
      fullPath: '/cronograma/publico/$token'
      preLoaderRoute: typeof CronogramaPublicoTokenRouteImport
      parentRoute: typeof CronogramaRoute
    }
  }
}

interface CronogramaRouteChildren {
  CronogramaPublicoTokenRoute: typeof CronogramaPublicoTokenRoute
}

const CronogramaRouteChildren: CronogramaRouteChildren = {
  CronogramaPublicoTokenRoute: CronogramaPublicoTokenRoute,
}

const CronogramaRouteWithChildren = CronogramaRoute._addFileChildren(
  CronogramaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BacklogRoute: BacklogRoute,
  BloqueadoRoute: BloqueadoRoute,
  CronogramaRoute: CronogramaRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EscalaRoute: EscalaRoute,
  EstoqueRoute: EstoqueRoute,
  LoginRoute: LoginRoute,
  ManuaisRoute: ManuaisRoute,
  ManuaisAvaliacaoRoute: ManuaisAvaliacaoRoute,
  OiRoute: OiRoute,
  PendingRoute: PendingRoute,
  RegisterRoute: RegisterRoute,
  RelatorioRoute: RelatorioRoute,
  TestesRoute: TestesRoute,
  ApiEquipeOverrideRoute: ApiEquipeOverrideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
